#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ESP32_Wirieless_Display

include /home/jeb/esp/esp-idf/make/project.mk

